---
apiVersion: v1
kind: Service
metadata:
  name: ved-prod-flask-npservice
spec:
  type: NodePort
  selector:
    app: ved-prod-api
  ports:
  - name: ved-prod-flask-npservice-fport
    port: 5000
    targetPort: 5005
    nodePort: 30105