---
apiVersion: v1
kind: Service
metadata:
  name: ved-prod-api-service
  labels:
    username: ved
    env: prod
spec:
  type: ClusterIP
  selector:
    username: ved
    env: prod
    app: ved-prod-api
  ports:
  - name: ved-prod-api-port
    port: 5000
    targetPort: 5005