---
apiVersion: v1
kind: Service
metadata:
  name: ved-prod-db-service
  labels:
    name: ved
    env: prod
spec:
  type: ClusterIP
  selector:
    username: ved
    env: prod
    app: ved-prod-db
  ports:
  - name: ved-prod-db-port
    port: 6379
    targetPort: 6379