---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ved-test-db-pvc
  labels:
    username: ved
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi